apiVersion: iot.s4t.crossplane.io/v1alpha1
kind: Plugin
metadata:
  name: simple-logger
  namespace: default
spec:
  forProvider:
    name: "Simple Logger"
    code: |
      from iotronic_lightningrod.modules.plugins import Plugin
      from oslo_log import log as logging
      import time
      import random
      
      LOG = logging.getLogger(__name__)
      
      class Worker(Plugin.Plugin):
          def __init__(self, uuid, name, q_result=None, params=None):
              super(Worker, self).__init__(uuid, name, q_result, params)
              self.interval = int(params.get('interval', 10)) if params else 10
              
          def run(self):
              LOG.info("=" * 50)
              LOG.info(f"Plugin {self.name} STARTED")
              LOG.info(f"Interval: {self.interval} seconds")
              LOG.info(f"Parameters: {self.params}")
              LOG.info("=" * 50)
              
              counter = 0
              while self._is_running:
                  # Genera un valore casuale
                  value = round(random.uniform(0, 100), 2)
                  
                  # Stampa a log
                  LOG.info(f"[{counter}] Value: {value}")
                  
                  counter += 1
                  time.sleep(self.interval)
                  
              LOG.info("=" * 50)
              LOG.info(f"Plugin {self.name} STOPPED")
              LOG.info(f"Total iterations: {counter}")
              LOG.info("=" * 50)
              
              if self.q_result:
                  self.q_result.put(f"Completed: {counter} iterations")
    parameters:
      interval: 10
      description: "Simple logger plugin that prints values every N seconds"
  providerConfigRef:
    name: s4t-provider-domain
  deletionPolicy: Delete
