apiVersion: iot.s4t.crossplane.io/v1alpha1
kind: Plugin
metadata:
  name: simple-environmental-logger
  namespace: default
spec:
  forProvider:
    name: "Simple Environmental Logger"
    code: |
      from iotronic_lightningrod.modules.plugins import Plugin
      from oslo_log import log as logging
      import time
      import random
      
      LOG = logging.getLogger(__name__)
      
      class Worker(Plugin.Plugin):
          def __init__(self, uuid, name, q_result=None, params=None):
              super(Worker, self).__init__(uuid, name, q_result, params)
              self.interval = int(params.get('interval', 30)) if params else 30
              
          def run(self):
              LOG.info(f"Plugin {self.name} started with interval: {self.interval} seconds")
              LOG.info(f"Input parameters: {self.params}")
              
              iteration = 0
              while self._is_running:
                  # Simulate environmental data
                  temperature = round(18.0 + random.uniform(-2, 5), 1)
                  humidity = round(75.0 + random.uniform(-10, 15), 1)
                  pressure = round(1013.0 + random.uniform(-10, 10), 1)
                  
                  # Log the data
                  LOG.info(f"[{iteration}] Environmental Data - Temperature: {temperature}°C, Humidity: {humidity}%, Pressure: {pressure}hPa")
                  
                  iteration += 1
                  time.sleep(self.interval)
                  
              LOG.info(f"Plugin {self.name} stopped")
              if self.q_result:
                  self.q_result.put("Plugin completed successfully")
    parameters:
      interval: 30
      description: "Simple environmental data logger plugin"
  providerConfigRef:
    name: s4t-provider-domain
  deletionPolicy: Delete
