FROM gcr.io/distroless/static@sha256:41972110a1c1a5c0b6adb283e8aa092c43c31f7c5d79b8656fbffff2c3e61f05
ARG TARGETOS
ARG TARGETARCH
COPY package-tmp/package.yaml /package.yaml
COPY _output/bin/linux_amd64/provider /usr/local/bin/crossplane-s4t-provider
USER 65532
ENTRYPOINT ["crossplane-s4t-provider"]
