apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: default
spec:
  deploymentTemplate:
    spec:
      template:
        spec:
          containers:
            - name: keystone-local-proxy
              image: alpine/socat:1.8.0.0
              args:
                - -d
                - -d
                - TCP-LISTEN:5000,fork,reuseaddr,bind=127.0.0.1
                - TCP:keystone.default.svc.cluster.local:5000
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
