---
# Esempio Avanzato: Board Plugin Injection
# Inietta un plugin su un board specifico
# IMPORTANTE: Sostituire BOARD_UUID_HERE e PLUGIN_UUID_HERE con valori reali
apiVersion: iot.s4t.crossplane.io/v1alpha1
kind: BoardPluginInjection
metadata:
  name: temperature-monitor-injection
  labels:
    app: iot-monitoring
    board: production-board-01
spec:
  providerConfigRef:
    name: s4t-provider-domain
  deletionPolicy: Delete
  forProvider:
    # UUID del board su cui iniettare il plugin
    # Ottenere l'UUID dal board esistente in Stack4Things
    boardUuid: "BOARD_UUID_HERE"
    # UUID del plugin da iniettare
    # Se il plugin è stato creato via Crossplane, l'UUID sarà nel status
    pluginUuid: "PLUGIN_UUID_HERE"

---
# Esempio: Injection con riferimento al plugin tramite annotation
# Questo esempio mostra come referenziare un plugin creato nello stesso namespace
apiVersion: iot.s4t.crossplane.io/v1alpha1
kind: BoardPluginInjection
metadata:
  name: simple-plugin-injection
  annotations:
    # Nota: Crossplane non supporta direttamente i riferimenti tra risorse
    # L'UUID del plugin deve essere ottenuto manualmente dal status del Plugin
    crossplane.io/external-name: "injection-simple-plugin"
spec:
  providerConfigRef:
    name: s4t-provider-domain
  deletionPolicy: Delete
  forProvider:
    boardUuid: "BOARD_UUID_HERE"
    pluginUuid: "PLUGIN_UUID_HERE"

