---
# Esempio Avanzato: Multi-Board Service Injection
# Inietta lo stesso service su multiple board
# Utile per deployment distribuiti su più dispositivi IoT

---
# Service condiviso
apiVersion: iot.s4t.crossplane.io/v1alpha1
kind: Service
metadata:
  name: shared-data-service
  labels:
    app: shared-service
    shared: "true"
spec:
  providerConfigRef:
    name: s4t-provider-domain
  deletionPolicy: Delete
  forProvider:
    name: "Shared Data Service"
    project: "admin"
    port: 5000
    protocol: "TCP"

---
# Injection su Board 1
apiVersion: iot.s4t.crossplane.io/v1alpha1
kind: BoardServiceInjection
metadata:
  name: shared-service-injection-board-01
  labels:
    app: shared-service
    board: board-01
    location: "site-a"
spec:
  providerConfigRef:
    name: s4t-provider-domain
  deletionPolicy: Delete
  forProvider:
    boardUuid: "BOARD_01_UUID_HERE"
    serviceUuid: "SHARED_SERVICE_UUID_HERE"

---
# Injection su Board 2
apiVersion: iot.s4t.crossplane.io/v1alpha1
kind: BoardServiceInjection
metadata:
  name: shared-service-injection-board-02
  labels:
    app: shared-service
    board: board-02
    location: "site-b"
spec:
  providerConfigRef:
    name: s4t-provider-domain
  deletionPolicy: Delete
  forProvider:
    boardUuid: "BOARD_02_UUID_HERE"
    serviceUuid: "SHARED_SERVICE_UUID_HERE"

---
# Injection su Board 3
apiVersion: iot.s4t.crossplane.io/v1alpha1
kind: BoardServiceInjection
metadata:
  name: shared-service-injection-board-03
  labels:
    app: shared-service
    board: board-03
    location: "site-c"
spec:
  providerConfigRef:
    name: s4t-provider-domain
  deletionPolicy: Delete
  forProvider:
    boardUuid: "BOARD_03_UUID_HERE"
    serviceUuid: "SHARED_SERVICE_UUID_HERE"

---
# Esempio: Deployment su Fleet
# Se si usa una Fleet, si può iniettare il service su tutti i board della fleet
# Nota: Questo richiede di ottenere gli UUID di tutti i board nella fleet
# e creare una BoardServiceInjection per ciascuno

