apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unime-iotronic-db-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi